openapi: 3.0.3
info:
  title: Sophrosyne - Action Service API
  description: |-
    This API document describes the available Sophrosyne Action Service APIs
  termsOfService: TBD
  contact:
    email:
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.1.0
externalDocs:
  description: Sophrosyne Core docs
  url: TBD
tags:
  - name: action
    description: Sophrosyne action operation
paths:
  /int/user/action:
    post:
      tags:
        - action
      summary: Create action
      description: This can only be done by the logged in user with admin rights.
      operationId: createAction
      requestBody:
        description: Creates action
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Action'
      responses:
        '200':
          description: successful operation
        '401':
          description: Unauthorized
  /int/user/actions:
    get:
      tags:
        - action
      summary: Get all actions
      description: ''
      operationId: getActions
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Action'
        '401':
          description: Unauthorized
  /int/user/action/{id}:
    get:
      tags:
        - action
      summary: Get action by id
      description: ''
      operationId: getActionById
      parameters:
        - name: id
          in: path
          description: 'The id that needs to be fetched'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Action'
        '400':
          description: Invalid id supplied
        '401':
          description: Unauthorized
        '404':
          description: Action not found
    put:
      tags:
        - action
      summary: Update action
      operationId: updateAction
      parameters:
        - name: id
          in: path
          description: 'The id that needs to be fetched'
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Action'
      responses:
        default:
          description: successful operation
        '401':
          description: Unauthorized
        '404':
          description: Action not found
    delete:
      tags:
        - action
      summary: Delete action
      operationId: deleteAction
      parameters:
        - name: id
          in: path
          description: 'The id that needs to be fetched'
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid id supplied
        '401':
          description: Unauthorized
        '404':
          description: Action not found
components:
  schemas:
    Action:
      type: object
      properties:
        id:
          type: string
          example: id_1
        name:
          type: string
          example: AnsibleDeployment
        description:
          type: string
          example: This starts the deployment of your data center with Ansible
        command:
          type: string
          example: ansible-playbook
        version:
          type: string
          example: v.1.2.3
        postExecutionLogFilePath:
          type: string
          example: /etc/ansible/ansible.log
        allowedApikeys:
          type: array
          items:
            type: string
        requiresConfirmation:
          type: int
          example: 1
        muted:
          type: int
          example: 1
      required:
        - name
        - command
