openapi: 3.0.3
info:
  title: Sophrosyne - Action Recommendation Service API
  description: |-
    This API document describes the available Sophrosyne Action Recommendation Service APIs
  version: 1.0.0
externalDocs:
  description: Sophrosyne Core docs
  url: TBD
tags:
  - name: action_recommendation
    description: Sophrosyne action recommendation operation
paths:
  /int/user/actionrecommendation:
    post:
      tags:
        - action_recommendation
      summary: Create an action recommendation
      description: This can only be done by the logged in user with admin rights.
      operationId: createActionRecommendation
      requestBody:
        description: Creates action recommendation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActionRecommendation'
      responses:
        '200':
          description: successful operation
        '401':
          description: Unauthorized
  /int/user/actionrecommendations:
    get:
      tags:
        - action_recommendation
      summary: Get all actions
      description: ''
      operationId: getActionRecommendations
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ActionRecommendation'
        '401':
          description: Unauthorized
  /int/user/actionrecommendation/{id}:
    get:
      tags:
        - action_recommendation
      summary: Get action recommendation by action recommendation id
      description: ''
      operationId: getActionRecommendationByActionId
      parameters:
        - name: id
          in: path
          description: 'The id that needs to be fetched'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionRecommendation'
        '400':
          description: Invalid action recommendation id supplied
        '401':
          description: Unauthorized
        '404':
          description: Action Recommendation not found
    put:
      tags:
        - action_recommendation
      summary: Update action recommendation
      operationId: updateActionRecommendation
      parameters:
        - name: id
          in: path
          description: 'The id that needs to be fetched'
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActionRecommendation'
      responses:
        default:
          description: successful operation
        '401':
          description: Unauthorized
        '404':
          description: Apikey not found
    delete:
      tags:
        - action_recommendation
      summary: Delete action recommendation
      operationId: deleteActionRecommendation
      parameters:
        - name: id
          in: path
          description: 'The id that needs to be fetched'
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid id supplied
        '401':
          description: Unauthorized
        '404':
          description: Action Recommendation not found
components:
  schemas:
    ActionRecommendation:
      type: object
      properties:
        id:
          type: string
          example: id_1
        name:
          type: string
          example: Fix it
        description:
          type: string
          example: Do this and that. It will fix it
        responsibleEntity:
          type: string
          example: John Doe
        contactInformation:
          type: string
          example: support@support.com
        additionalDocumentation:
          type: string
          format: byte
        allowedApikeys:
          type: array
          items:
            type: string
      required:
        - name
        - description