openapi: 3.0.3
info:
  title: Sophrosyne - Apikey Service API
  description: |-
    This API document describes the available Sophrosyne Apikey Service APIs
  termsOfService: TBD
  contact:
    email:
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.1.0
externalDocs:
  description: Sophrosyne Core docs
  url: TBD
tags:
  - name: api
    description: Sophrosyne apikey operation
paths:
  /int/admin/apikey:
    post:
      tags:
        - api
      summary: Create apikey
      description: This can only be done by the logged in user with admin rights.
      operationId: generateNewAPIToken
      requestBody:
        description: Creates apikey
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Apikey'
      responses:
        '200':
          description: successful operation
        '401':
          description: Unauthorized
  /int/admin/apikey/{apikeyname}:
    get:
      tags:
        - apikey
      summary: Get apikey by apikeyname
      description: ''
      operationId: getApikeyByApikeyName
      parameters:
        - name: apikeyname
          in: path
          description: 'The name that needs to be fetched'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApikeyView'
        '400':
          description: Invalid apikeyname supplied
        '401':
          description: Unauthorized
        '404':
          description: Apikey not found
    put:
      tags:
        - apikey
      summary: Update apikey
      operationId: updateApikey
      parameters:
        - name: apikeyname
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: successful operation
        '401':
          description: Unauthorized
        '404':
          description: Apikey not found
    delete:
      tags:
        - apikey
      summary: Delete apikey
      operationId: deleteApikey
      parameters:
        - name: apikeyname
          in: path
          description: The name that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid apikeyname supplied
        '401':
          description: Unauthorized
        '404':
          description: Apikey not found
  /int/user/apikeys:
    get:
      tags:
        - apikey
      summary: Get all apikeys
      description: ''
      operationId: getApikeys
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApikeyView'
        '401':
          description: Unauthorized
  /int/admin/apikey/{apikeyname}/activate:
    put:
      tags:
        - apikey
      summary: Activate apikey by apikeyname
      description: ''
      operationId: activateApikeyByApikeyName
      parameters:
        - name: apikeyname
          in: path
          description: 'The name that needs to be fetched'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApikeyView'
        '400':
          description: Invalid apikeyname supplied
        '401':
          description: Unauthorized
        '404':
          description: Apikey not found
  /int/admin/apikey/{apikeyname}/deactivate:
    put:
      tags:
        - apikey
      summary: Deactivate apikey by apikeyname
      description: ''
      operationId: deactivateApikeyByApikeyName
      parameters:
        - name: apikeyname
          in: path
          description: 'The name that needs to be fetched'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApikeyView'
        '400':
          description: Invalid apikeyname supplied
        '401':
          description: Unauthorized
        '404':
          description: Apikey not found
  /int/admin/apikeys/nuke:
    put:
      tags:
        - apikey
      summary: Deactivate all apikeys (Nuke)
      description: ''
      operationId: deactivateAllApikeys
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApikeyView'
        '401':
          description: Unauthorized
components:
  schemas:
    Apikey:
      type: object
      properties:
        apikeyname:
          type: string
          example: ApikeyForProjectTopSecret
        apikeydescription:
          type: string
          example: This key enables the execution of top secret ansible tasks
        apikeyactive:
          type: int
          example: true
    ApikeyView:
      type: object
      properties:
        apikeyname:
          type: string
          example: ApikeyForProjectTopSecret
        apikeydescription:
          type: string
          example: This key enables the exxecution of top secret ansible tasks
        apikeyactive:
          type: int
          example: 1
        apikey:
          type: string
          example: kjn3wrb325hwrn3jn5kntw4kjt6n3kn64entkentke4nt4tn
