openapi: 3.0.3
info:
  title: Sophrosyne - Control Panel Service API
  description: |-
    This API document describes the available Sophrosyne Control Panel Service APIs
  termsOfService: TBD
  contact:
    email:
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Sophrosyne Core docs
  url: TBD
tags:
  - name: control_panel_dashboard_group
    description: Sophrosyne control panel dashboard group operation
paths:
  /int/user/controlpanel:
    post:
      tags:
        - control_panel
      summary: Create control panel
      description: This can only be done by the logged in user with user rights or higher.
      operationId: createControlPanel
      requestBody:
        description: Creates control panel
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ControlPanel'
      responses:
        '200':
          description: successful operation
        '401':
          description: Unauthorized
  /int/user/controlpanels:
    get:
      tags:
        - control_panel
      summary: Get all control panels
      description: ''
      operationId: getControlPanels
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ControlPanel'
        '401':
          description: Unauthorized
  /int/user/controlpanel/{id}:
    get:
      tags:
        - control_panel
      summary: Get Control Panel by control panel id
      description: ''
      operationId: getControlPanelById
      parameters:
        - name: id
          in: path
          description: 'The id that needs to be fetched'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ControlPanel'
        '400':
          description: Invalid id supplied
        '401':
          description: Unauthorized
        '404':
          description: Control Panel not found
    put:
      tags:
        - control_panel
      summary: Update Control Panel
      operationId: updateControlPanel
      parameters:
        - name: id
          in: path
          description: 'The id that needs to be fetched'
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ControlPanel'
      responses:
        default:
          description: successful operation
        '401':
          description: Unauthorized
        '404':
          description: Control Panel not found
    delete:
      tags:
        - control_panel
      summary: Delete Control Panel
      operationId: deleteControlPanel
      parameters:
        - name: id
          in: path
          description: 'The id that needs to be fetched'
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid id supplied
        '401':
          description: Unauthorized
        '404':
          description: Control Panel not found
components:
  schemas:
    ControlPanel:
      type: object
      properties:
        id:
          type: string
          example: id_1
        name:
          type: string
          example: Control Panel 1
        description:
          type: string
          example: All Deployment related Actions
        associatedUsers:
          type: array
          items:
            type: string
            example: user_id_1
        associatedControlPanelDashboards:
          type: array
          items:
            type: string
            example: control_panel_dashboard_id_1
        associatedControlPanelDashboardObjects:
          type: array
          items:
            type: object
      required:
        - name