openapi: 3.0.3
info:
  title: Sophrosyne - Configuration Service API
  description: |-
    This API document describes the available Sophrosyne Configuration Service APIs
  version: 1.0.0
tags:
  - name: configuration
    description: Sophrosyne internal configuration operations
paths:
  /int/admin/configuration/export:
    get:
      tags:
        - configuration
      summary: Get configuration
      description: ''
      operationId: getConfigurationData
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Unauthorized
  /int/admin/configuration/import:
    post:
      tags:
        - configuration
      summary: Triggers the import of the sophrosyne.json configuration without erasing the previous imported configuration
      description: 'Conflicting entries between config sophrosyne.json and current sophrosyne instance configuration may lead to the skipping of entries import. Use /import/force endpoint to force the configuration import'
      operationId: importSophrosyneConfigurationFromFile
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
        '207':
          description: partially successful operation
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
  /int/admin/configuration/import/force:
    post:
      tags:
        - configuration
      summary: Triggers the import of the sophrosyne.json configuration with erasing the previous imported configuration
      description: 'Ensures the import of the complete sophrosyne.json config at the risk of loosing local changes. Export and backup the current sophrosyne config beforehand to eliminate the risk'
      operationId: importSophrosyneConfigurationFromFileForce
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
        '207':
          description: partially successful operation
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized