name: Sophrosyne CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 25 with OpenJDK
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file ./core/pom.xml

    - name: Run Tests
      run: mvn test --file ./core/pom.xml